name: Security Pipeline
on: [push]

jobs:
  security-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
        
    - name: Install Dependencies
      run: go mod download
      
    - name: Start Web Server
      run: go run main.go &
      
    - name: Wait for Server
      run: sleep 10
      
    - name: OWASP ZAP Scan
      uses: zaproxy/action-full-scan@v0.2.0
      with:
        target: 'http://localhost:8080'
        
    - name: Snyk Security Scan
      uses: snyk/actions/setup@master
      with:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
